# Generated by Django 3.2 on 2021-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='link_to_img',
            field=models.TextField(default='/static/images/default_pfp.jpg'),
        ),
    ]
