# Generated by Django 3.2 on 2021-05-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_groups_link_to_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('members', models.TextField()),
                ('invitations', models.TextField()),
                ('admins', models.TextField()),
                ('chats', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('closed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ServersMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField()),
                ('chat_id', models.IntegerField()),
                ('message', models.TextField()),
                ('sender_id', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
