# Generated by Django 3.2 on 2021-05-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_servers_serversmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups_inv',
            field=models.TextField(default=''),
        ),
    ]
