# Generated by Django 3.2 on 2021-05-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_chats_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='datetime',
            field=models.TextField(),
        ),
    ]
