# Generated by Django 3.2 on 2021-05-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210516_0236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chats',
            new_name='Messages',
        ),
    ]
