# Generated by Django 3.2 on 2021-05-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_messages_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='link_to_img',
            field=models.TextField(default='/static/images/default_pfp.jpg'),
        ),
    ]
