# Generated by Django 3.2 on 2021-05-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_servers_link_to_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='servers',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='servers_inv',
            field=models.TextField(default=''),
        ),
    ]
