# Generated by Django 3.2 on 2021-05-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210516_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='creator_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
