# Generated by Django 3.2 on 2021-05-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_serverschats'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='music_visible',
            field=models.BooleanField(default=True),
        ),
    ]
