# Generated by Django 3.2 on 2021-05-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210516_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileposts',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
