# Generated by Django 3.2 on 2021-05-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_userprofileposts_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='groupsposts',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='servers',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='serverschats',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='serversmessages',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
