# Generated by Django 3.2 on 2021-05-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_profile_group_posts_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsposts',
            name='liked_by',
            field=models.TextField(default=''),
        ),
    ]
