# Generated by Django 3.2 on 2021-05-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_groupsposts_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileposts',
            name='liked_by',
            field=models.TextField(default=''),
        ),
    ]
