# Generated by Django 3.2 on 2021-05-28 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_messages_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.TextField()),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('members', models.TextField()),
                ('invitations', models.TextField()),
                ('admins', models.TextField()),
                ('chats', models.TextField()),
                ('link_to_img', models.TextField(default='/static/images/default_pfp.jpg')),
                ('datetime', models.DateTimeField()),
                ('closed', models.BooleanField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServerChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.server')),
            ],
        ),
        migrations.RenameModel(
            old_name='GalleryImages',
            new_name='GalleryImage',
        ),
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='GroupsPosts',
            new_name='GroupPost',
        ),
        migrations.RenameModel(
            old_name='ServersMessages',
            new_name='ServerMessage',
        ),
        migrations.RenameModel(
            old_name='UserProfilePosts',
            new_name='UserPost',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Servers',
        ),
        migrations.DeleteModel(
            name='ServersChats',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
