# Generated by Django 3.2 on 2021-05-28 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_auto_20210528_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='user_id',
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grouppost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
