# Generated by Django 3.2 on 2021-05-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210528_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
    ]
