# Generated by Django 3.2 on 2021-05-28 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0028_rename_group_name_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userpost',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
