# Generated by Django 3.2 on 2021-05-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210528_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='link_to_png',
            new_name='link_to_img',
        ),
    ]
