# Generated by Django 3.2 on 2021-05-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_link_to_png_userpost_link_to_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='music_visible',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='age_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='gallery_visible',
            field=models.BooleanField(default=True),
        ),
    ]
