# Generated by Django 3.2 on 2021-05-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210528_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bans',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='server',
            name='bans',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='invitations',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='server',
            name='invitations',
            field=models.TextField(default=''),
        ),
    ]
